### ISSUE TITLE
Version 2.x Release Todo

### ISSUE THREAD

**Issue by aneek** [aneek/rate_limiter#3]
- [x] Missing configuration and help link in module page - https://www.drupal.org/node/2727191
- [x] Coding Standard issues - https://www.drupal.org/node/2885396
- [ ] Allow admins to setup rate limiter counter in Database table instead of Cache. (Give them a choice)
- [ ] Doesn't work for post API calls - https://www.drupal.org/node/2920325
- [ ] Bearer Token support for OAuth2.
- [ ] Add full test coverage
